### ISSUE TITLE
(Bug): Bot crashes when player gets destroyed (only while using NodeLink)

### ISSUE THREAD

**Issue by heapyxyz** [1Lucas1apk/moonlink.js#112]
Code for a command to reproduce the crash (probably not necessary):
```js
import { CommandInteraction } from "discord.js"
import { Discord, Slash } from "discordx"
import { bot } from "../index.js"

@Discord()
export class Leave {
  @Slash({
    description: "Leaves voice channel",
    name: "leave",
  })
  async leave(interaction: CommandInteraction): Promise<void> {
    await interaction.deferReply()

    var player = bot.moon.players.get(interaction.guildId!)

    if (!player) {
      await interaction.editReply({
        content: "Not connected to a voice channel",
      })

      return
    }

    await player.destroy()
    await interaction.editReply("Left voice channel")
  }
}
```
Here's the error I get (and then the script crashes):
```
undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:5472:19)
    at successSteps (node:internal/deps/undici/undici:5454:27)
    at consumeBody (node:internal/deps/undici/undici:5460:9)
    at _Response.json (node:internal/deps/undici/undici:5400:18)
    at /home/heapy/simple.ts/simple.ts/node_modules/moonlink.js/dist/src/Utils.js:12:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Rest.destroy (/home/heapy/simple.ts/simple.ts/node_modules/moonlink.js/dist/src/entities/Rest.js:45:23)
    at async PlayerManager.delete (/home/heapy/simple.ts/simple.ts/node_modules/moonlink.js/dist/src/management/PlayerManager.js:43:9)
```

This is happening because of [this line](https://github.com/Ecliptia/moonlink.js/blob/ddafc72e151af9dc7fe84a8aad2f77d1b26b2274/src/entities/Player.ts#L315)
```js 
this.manager.players.delete(this.guildId);
```

This is what NodeLink prints:
```
[deletePlayer]: Received a request from client.
 Params: "/v4/sessions/aEzxNMYiwm7b3EIj/players/885904835197681774"
 Headers: {"host":"REDACTED","connection":"keep-alive","authorization":"REDACTED","accept":"application/json","user-agent":"Moonlink.js/4.0.1 (FALLING STAR)","content-type":"application/json","accept-language":"*","sec-fetch-mode":"cors","accept-encoding":"gzip, deflate"}
[websocket]: A connection was closed with a client.
 Code: 1006
 Reason: No reason provided
```
NodeLink version: [commit 86f3189](https://github.com/PerformanC/NodeLink/commit/86f3189627dd63a66bae382d5453ae6c5f7730a1)
moonlink.js version: [4.0.1](https://www.npmjs.com/package/moonlink.js/v/4.0.1)
discord.js version: [14.15.3](https://www.npmjs.com/package/discord.js/v/14.15.3)

**Comment by heapyxyz** [comment]
```ts
export function makeRequest<T>(url: string, options: RequestInit): Promise<T> {
    let request = fetch(url, options)
    .then((res) => res.json().catch(() => res.text()))
    .then((json) => json as T)
    
    if (!request) return;
    return request;
}
  ```
I'm pretty confused because NodeLink doesn't crash and prints that a connection was closed. It might be because the script crashed though. 😅

**Comment by heapyxyz** [comment]
[*NodeLink's code for deleting sessions*](https://github.com/PerformanC/NodeLink/blob/86f3189627dd63a66bae382d5453ae6c5f7730a1/src/connection/handler.js#L506)
Note that NodeLink sends back a `null` response.
```js
    if (req.method === 'DELETE') {
      if (!player) {
        debugLog('deletePlayer', 1, { params: parsedUrl.pathname, headers: req.headers, error: 'The provided guildId doesn\'t exist.' })

        return sendResponse(req, res, {
          timestamp: Date.now(),
          status: 404,
          trace: new Error().stack,
          message: 'The provided guildId doesn\'t exist.',
          path: parsedUrl.pathname
        }, 404)
      }

      player.destroy()
      client.players.delete(guildId)

      debugLog('deletePlayer', 1, { params: parsedUrl.pathname, headers: req.headers })

      return sendResponse(req, res, null, 204)
    }
```

**Comment by 1Lucas1apk** [comment]
desinstala o pacote e instale usando o link do repositorio do github

npm i https://github.com/Ecliptia/moonlink.js

**Comment by 1Lucas1apk** [comment]
translation: uninstall the package and install using the github repository link

npm i https://github.com/Ecliptia/moonlink.js

**Comment by heapyxyz** [comment]
Okay, it works fine now - however NodeLink detects an error:
```
[deletePlayer]: Detected an error in a request: The provided guildId doesn't exist.
```
Should I even worry about it if everything works fine? Lol
You can close this issue btw.

**Comment by 1Lucas1apk** [comment]
I'm not sure, but you can hire support from performanC

**Comment by heapyxyz** [comment]
I see, thanks for help once again! :)
