### ISSUE TITLE
(Bug): voiceRegion and empty

### ISSUE THREAD

**Issue by xotakfr** [1Lucas1apk/moonlink.js#72]
**Describe the bug**
The PlayerManager.cache attribute is empty (`{}`). This is causing issue with the `attemptConnection` method for that class ([file](https://github.com/Ecliptia/moonlink.js/blob/v3/dist/src/%40Managers/PlayerManager.js#L43))

**To Reproduce**
1. Launch bot with or without sharding (happen with both)
2. Try to connect/log PlayerManager
3. PlayerManager.cache is empty, leading to errors in PlayerManager

**Expected behavior**
The bot connects/The cache have the right values

**Screenshots**

Won't do a screenshot of my console, here's full console output : 

```
❯ node bot.js
�={"op":"ready","resumed":false,"sessionId":"ypvqy2s4x5lbok5a"}
�~{"op":"stats","frameStats":null,"players":0,"playingPlayers":0,"uptime":1682695,"memory":{"free":77562136,"used":178290408,"allocated":255852544,"reservable":1520435200},"cpu":{"cores":8,"systemLoad":0.03271721460976983,"lavalinkLoad":0.0011935803738660987}}
[20:32:50.229] WARN (9581): UNSHARDED
[20:32:50.230] INFO (9581): Ready! Logged in as Un Bot de test#5999
[20:32:50.244] INFO (9581): localhost was connected. Lavalink ready
<ref *1> PlayerManager {
  _manager: <ref *2> MoonlinkManager {
    _events: [Object: null prototype] {
      nodeCreate: [Function (anonymous)],
      trackStart: [Array]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    clientId: '715944203430920334',
    _nodes: [ [Object] ],
    _SPayload: [Function (anonymous)],
    players: [Circular *1],
    nodes: NodeManager {
      initiated: true,
      _manager: [Circular *2],
      map: [Map]
    },
    version: '3.2.88',
    options: {
      clientName: '@Moonlink/3.2.88 (https://github.com/Ecliptia/moonlink.js)',
      clientId: '715944203430920334'
    },
    initiated: true,
    [Symbol(shapeMode)]: false,
    [Symbol(kCapture)]: false
  },
  cache: {},
  voices: {}
}
�~{"op":"stats","frameStats":null,"players":0,"playingPlayers":0,"uptime":1742695,"memory":{"free":77227960,"used":178624584,"allocated":255852544,"reservable":1520435200},"cpu":{"cores":8,"systemLoad":0.02032248631939513,"lavalinkLoad":0.0012708121531307811}}
�~{"op":"stats","frameStats":null,"players":0,"playingPlayers":0,"uptime":1802695,"memory":{"free":76929384,"used":178923160,"allocated":255852544,"reservable":1520435200},"cpu":{"cores":8,"systemLoad":0.010754709100781022,"lavalinkLoad":0.0012917097236574552}}
�~{"op":"stats","frameStats":null,"players":0,"playingPlayers":0,"uptime":1862695,"memory":{"free":76743864,"used":179108680,"allocated":255852544,"reservable":1520435200},"cpu":{"cores":8,"systemLoad":0.01025266235122155,"lavalinkLoad":0.0012708121531307811}}
�~{"op":"stats","frameStats":null,"players":0,"playingPlayers":0,"uptime":1922695,"memory":{"free":76195776,"used":179656768,"allocated":255852544,"reservable":1520435200},"cpu":{"cores":8,"systemLoad":0.010880233893703664,"lavalinkLoad":0.0012916666666666667}}
/home/user/yadb/node_modules/moonlink.js/dist/src/@Managers/PlayerManager.js:76
                this.cache[guildId].voiceRegion = voiceRegion[1];
                                                             ^

TypeError: Cannot read properties of null (reading '1')
    at PlayerManager.attemptConnection (/home/user/yadb/node_modules/moonlink.js/dist/src/@Managers/PlayerManager.js:76:62)
    at MoonlinkManager.packetUpdate (/home/user/yadb/node_modules/moonlink.js/dist/src/@Managers/MoonlinkManager.js:144:26)
    at Client.<anonymous> (/home/user/yadb/bot.js:115:17)
    at Client.emit (node:events:519:28)
    at WebSocketManager.<anonymous> (/home/user/yadb/node_modules/discord.js/src/client/websocket/WebSocketManager.js:236:19)
    at WebSocketManager.emit (/home/user/yadb/node_modules/@vladfrangu/async_event_emitter/dist/index.js:282:31)
    at WebSocketShard.<anonymous> (/home/user/yadb/node_modules/@discordjs/ws/dist/index.js:1173:51)
    at WebSocketShard.emit (/home/user/yadb/node_modules/@vladfrangu/async_event_emitter/dist/index.js:282:31)
    at WebSocketShard.onMessage (/home/user/yadb/node_modules/@discordjs/ws/dist/index.js:988:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v21.6.1
```

Looks like voices is not populated too

Tried with the example script, also broken.

Seems that the code introduced in 647d8aa5d3e0560c0209249924ab1a6031b8f37b broke

**Additional context**
None

**Comment by 1Lucas1apk** [comment]
I'll do an analysis, and I'll get back to you shortly.

**Comment by 1Lucas1apk** [comment]
Variable 'voiceRegion' may have a null value originated from the expression 'null'. But its property is accessed at this point without null check.  

I will correct this error!

**Comment by 1Lucas1apk** [comment]
Theoretically resolved

**Comment by xotakfr** [comment]
I can confirm, it works now. Thanks.
