### ISSUE TITLE
(Bug): player.destroy() causes error, Key path doesn't exist

### ISSUE THREAD

**Issue by crackedpotato007** [1Lucas1apk/moonlink.js#93]
**Describe the bug**
`player.destroy()` causes a error which could cause the execution to stop if not handled properly.

**To Reproduce**
use the player.destroy() function, for eg when all members leave

**Expected behavior**
Player should be destroyed without an errors

**Additional context**
Error
```
C:\Users\Website\Desktop\Musico\node_modules\moonlink.js\dist\src\@Utils\MoonlinkDatabase.js:52                               keys.forEach(k => {                                                                                                        ^                                                                                                        Error: @Moonlink(Database) - Key path "players.1077418717668982854" does not exist                                        at C:\Users\Website\Desktop\Musico\node_modules\moonlink.js\dist\src\@Utils\MoonlinkDatabase.js:57:23                 at Array.forEach (<anonymous>)                                                                                        at MoonlinkDatabase.delete (C:\Users\Website\Desktop\Musico\node_modules\moonlink.js\dist\src\@Utils\MoonlinkDatabase.js:52:14)                                                                                                             at PlayerManager.delete (C:\Users\Website\Desktop\Musico\node_modules\moonlink.js\dist\src\@Managers\PlayerManager.js:140:36)                                                                                                               at MoonlinkPlayer.destroy (C:\Users\Website\Desktop\Musico\node_modules\moonlink.js\dist\src\@Entities\MoonlinkPlayer.js:308:36)                                                                                                            at processTicksAndRejections (node:internal/process/task_queues:95:5)                                                                                                                                                                  
```

Moon events
```
    this.moon.on("nodeCreate", (node) => {
      console.log(`${node.host} was connected, and the magic is in the air`);
    });
    this.moon.on("trackEnd", async (player, track) => {
      // Sending a message when the track finishes playing
      let channel = this.channels.cache.get(player.textChannel);
      if (!channel) return;
      if (channel.type === ChannelType.GuildText) {
        channel.send(`${track.title} has finished playing, spreading joy`);
      }
    });
    this.moon.on("trackStart", async (player, track) => {
      // Sending a message when the track starts playing
      let channel = this.channels.cache.get(player.textChannel);
      if (!channel) return;
      if (channel.type === ChannelType.GuildText) {
        channel.send(`${track.title} is now playing!`);
      }
    });
    this.on("raw", (data) => {
      // Updating the Moonlink.js package with the necessary data
      this.moon.packetUpdate(data);
    });
```

player.destroy function

```
  console.log("Voice state has been updated");
    const chanID = oldState.channelId;
    if (!chanID) return;
    const vc = await newState.guild.channels.fetch(chanID);
    if (vc?.type !== ChannelType.GuildVoice) return;
    const player = client.moon.players.get(newState.guild.id);
    if (!player) return;
    if (!vc) return;
    console.log(vc.members.size);
    if (oldState.channelId === player.voiceChannel) {
      if (vc.members.size === 1) {
        const textchannel = await newState.guild.channels.fetch(
          player.textChannel
        );
        if (!textchannel) return;
        if (textchannel.type !== ChannelType.GuildText) return;
        await textchannel.send(
          "I have left the voice channel because I was lonely"
        );

        await player.destroy();
      }
    }
```

**Comment by 1Lucas1apk** [comment]
Thanks for reporting the bug, it will be fixed in the next version

**Comment by 1Lucas1apk** [comment]
Issue coming from: https://github.com/Ecliptia/moonlink.js/blob/2466a49b0bfc84722a463ade552ac9fbbe4f24e8/src/%40Managers/PlayerManager.ts#L223

Trying to delete non-existent data

**Comment by crackedpotato007** [comment]
Beat me to it, Was just about to post that i found the issue :)
