### ISSUE TITLE
(Bug): Moonlink(Database) - Failed to save data

### ISSUE THREAD

**Issue by kiss8981** [1Lucas1apk/moonlink.js#98]
**Describe the bug**
After about a day of leaving the bot on, an error occurs in the database. If an error occurs in the database and you run it again, the error `Error @Moonlink(Database) - Failed to fetch data (Error):` will occur, but if you access the database folder and run the bot again, it will operate normally.

**To Reproduce**
1. Turn on the bot and leave it for about a day.
2. Throw Moonlink(Database) Error - Data storage failure error occurs.

**Expected behavior**
Even if the bot is turned on for a long time, data must continue to be saved without `Error: @Moonlink(Database) - Failed to save data`.

**Screenshots**
```
2024-03-11 12:47:57.352 [ ERROR ] [ Bot ]  Error: @Moonlink(Database) - Failed to save data
    at MoonlinkDatabase.save (C:\Users\Administrator\discord\node_modules\moonlink.js\dist\src@Utils\MoonlinkDatabase.js:109:19)
    at MoonlinkDatabase.set (C:\Users\Administrator\discord\node_modules\moonlink.js\dist\src@Utils\MoonlinkDatabase.js:23:14)
    at MoonlinkQueue.setQueue (C:\Users\Administrator\discord\node_modules\moonlink.js\dist\src@Entities\MoonlinkQueue.js:96:17)
    at MoonlinkQueue.add (C:\Users\Administrator\discord\node_modules\moonlink.js\dist\src@Entities\MoonlinkQueue.js:28:14)
    at SlashCommand.execute (C:\Users\Administrator\discord\src\commands\music\play.ts:95:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Event.execute (C:\Users\Administrator\discord\src\events\onInteraction.ts:21:13)
```

```
2024-03-11 12:47:57.387 [ ERROR ] [ main ]
 Error  EMFILE: too many open files, open 'C:\Users\Administrator\discord\logs\latest.log', -4066, EMFILE, open, C:\Users\Administrator\discord\logs\latest.log
error stack:

2024-03-11 12:47:57.401 [ ERROR ] [ main ]
 Error  ENOENT: no such file or directory, mkdir 'C:\Users\Administrator\discord\20240311-0000-01-C:\Users\Administrator\discord\logs', -4058, ENOENT, mkdir, C:\Users\Administrator\discord\20240311-0000-01-C:\Users\Administrator\discord\logs
error stack:
```

**Additional context**
I think the corresponding error occurs, and in my bot log system, `Error  EMFILE: too many open files, open 'C:\Users\Administrator\discord\logs\latest.log', -4066, EMFILE, open, C:\Users\Administrator\discord\logs\latest.log
error stack:` error, it seems that an error occurred while saving the file.

**Comment by 1Lucas1apk** [comment]
This problem is related to your programming environment

**Comment by 1Lucas1apk** [comment]
But I can also work around the problem within the database

**Comment by kiss8981** [comment]
How should we solve this problem?

**Comment by 1Lucas1apk** [comment]
I analyzed it better and realized that the error is that I opened but did not close, I will correct this in the next commit, thank you very much for reporting it

**Comment by 1Lucas1apk** [comment]
Could you test it to see if it fixed your problem? 

Uninstall seek and install using `npm install Ecliptia/moonlink.js#development`

**Comment by kiss8981** [comment]
I will test it and let you know if any errors occur. thank you

**Comment by kiss8981** [comment]
```
2024-03-12 12:55:39.650 [ ERROR ] [ Bot ]  Error: @Moonlink(Database) - Failed to save data, error:
    at MoonlinkDatabase.save (C:\Users\Administrator\discord\node_modules\moonlink.js\dist\src@Utils\MoonlinkDatabase.js:113:19)
    at MoonlinkDatabase.set (C:\Users\Administrator\discord\node_modules\moonlink.js\dist\src@Utils\MoonlinkDatabase.js:23:14)
    at MoonlinkQueue.setQueue (C:\Users\Administrator\discord\node_modules\moonlink.js\dist\src@Entities\MoonlinkQueue.js:96:17)
    at MoonlinkQueue.add (C:\Users\Administrator\discord\node_modules\moonlink.js\dist\src@Entities\MoonlinkQueue.js:28:14)
    at SlashCommand.execute (C:\Users\Administrator\discord\src\commands\music\play.ts:95:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Event.execute (C:\Users\Administrator\discord\src\events\onInteraction.ts:21:13)
2024-03-12 12:55:39.691 [ ERROR ] [ main ]
 Error  EMFILE: too many open files, open 'C:\Users\Administrator\discord\logs\latest.log', -4066, EMFILE, open, C:\Users\Administrator\discord\logs\latest.log
error stack:
```
```
2024-03-12 12:58:13.415 [ ERROR ] [ main ]
 Error  @Moonlink(Database) - Failed to save data, error:
error stack:
  • \node_modules\moonlink.js\dist\src@Utils\MoonlinkDatabase.js       MoonlinkDatabase.save
        \node_modules\moonlink.js\dist\src@Utils\MoonlinkDatabase.js:113
  • \node_modules\moonlink.js\dist\src@Utils\MoonlinkDatabase.js       MoonlinkDatabase.set
        \node_modules\moonlink.js\dist\src@Utils\MoonlinkDatabase.js:23
  • \node_modules\moonlink.js\dist\src@Entities\MoonlinkQueue.js       MoonlinkQueue.setQueue
        \node_modules\moonlink.js\dist\src@Entities\MoonlinkQueue.js:96
  • \node_modules\moonlink.js\dist\src@Entities\MoonlinkQueue.js       MoonlinkQueue.clear
        \node_modules\moonlink.js\dist\src@Entities\MoonlinkQueue.js:57
  • \src\events\onVoiceStateUpdate.ts   musicBotDestroy
        \src\events\onVoiceStateUpdate.ts:25
  • \src\events\onVoiceStateUpdate.ts   Event.mem
        \src\events\onVoiceStateUpdate.ts:9
  • \src\managers\EventManager.ts       BotClient.<anonymous>
        \src\managers\EventManager.ts:69
```

The same error occurs as before. This may be an error due to the Windows environment.
